BASELINE_IMAGENAME=mikinglang/baseline
MIKING_IMAGENAME=mikinglang/miking

# NOTE: VERSION_SUFFIX to be set in subfolders' Makefile
LATEST_VERSION=latest-$(VERSION_SUFFIX)
MIKING_IMAGEVERSION=dev3-$(VERSION_SUFFIX)
BASELINE_IMAGEVERSION=v1-$(VERSION_SUFFIX)

MIKING_COMMIT="3fe36ceec872e15fddb98e3eb868a171983ab13c"
