BASELINE_IMAGENAME=mikinglang/baseline
MIKING_IMAGENAME=mikinglang/miking

# NOTE: VERSION_SUFFIX to be set in subfolders' Makefile
LATEST_VERSION=latest-$(VERSION_SUFFIX)
MIKING_IMAGEVERSION=dev6-$(VERSION_SUFFIX)
BASELINE_IMAGEVERSION=v4-$(VERSION_SUFFIX)

MIKING_COMMIT="f649b2a63572964340ba066bdbab5210259933e8"
