BASELINE_IMAGENAME=mikinglang/baseline
MIKING_IMAGENAME=mikinglang/miking

# NOTE: VERSION_SUFFIX to be set in subfolders' Makefile
LATEST_VERSION=latest-$(VERSION_SUFFIX)
MIKING_IMAGEVERSION=dev4-$(VERSION_SUFFIX)
BASELINE_IMAGEVERSION=v2-$(VERSION_SUFFIX)

MIKING_COMMIT="d075c1b358e77dfa14c3c1fb770ca6a553f329e5"
