ARG BASELINE_IMAGE
FROM ${BASELINE_IMAGE}

# Download the latest version of the miking repository
RUN mkdir -p /src && cd /src && git clone https://github.com/miking-lang/miking

WORKDIR /src/miking

ARG MIKING_COMMIT
RUN git checkout ${MIKING_COMMIT}

# Apply patches if needed
# ADD patches/ /src/patches/
# Historic patch for javascript test case
# RUN patch -u test/js/make.sh < /src/patches/0001-*.patch

RUN eval $(opam env) && make install test-all clean

WORKDIR /root

CMD ["mi"]
