ARG BASELINE_IMAGE
FROM ${BASELINE_IMAGE}

# Download the latest version of the miking repository
ARG MIKING_GIT_REMOTE
RUN mkdir -p /src && cd /src && git clone ${MIKING_GIT_REMOTE}

WORKDIR /src/miking

ARG MIKING_GIT_COMMIT
RUN git checkout ${MIKING_GIT_COMMIT}

# Apply patches if needed
# ADD patches/ /src/patches/
# Historic patch for javascript test case
# RUN patch -u test/js/make.sh < /src/patches/0001-*.patch

RUN eval $(opam env) && make install test-all test-sundials clean

WORKDIR /root

CMD ["mi"]
